### PR TITLE
Fix compilation against LSP4E master

### PR DESCRIPTION
**Pull request by akurtakov**

### CODE REVIEW

**Comment by akurtakov** [comment]
@mickaelistria Is this the correct fix?

**Comment by vrubezhny** [comment]
@akurtakov Why you didn't change the lower limit for `o.e.lsp4e` depecdency?

https://github.com/redhat-developer/eclipseide-jdtls/blob/main/com.redhat.eclipseide.jdtlsclient/META-INF/MANIFEST.MF#LL11C5-L11C5

**Comment by akurtakov** [comment]
> @akurtakov Why you didn't change the lower limit for `o.e.lsp4e` depecdency?
> 
> https://github.com/redhat-developer/eclipseide-jdtls/blob/main/com.redhat.eclipseide.jdtlsclient/META-INF/MANIFEST.MF#LL11C5-L11C5
> 
> Should be like `0.17.0` ,no?

I don't think so I looked at old versions e.g. https://github.com/eclipse/lsp4e/blob/1ea5aa5cff4de79290fa8e7f86581ba655ae339c/org.eclipse.lsp4e/src/org/eclipse/lsp4e/command/CommandExecutor.java#L177 from  Nov 9, 2021 tag contains it.

**Comment by vrubezhny** [comment]
> I don't think so I looked at old versions e.g. https://github.com/eclipse/lsp4e/blob/1ea5aa5cff4de79290fa8e7f86581ba655ae339c/org.eclipse.lsp4e/src/org/eclipse/lsp4e/command/CommandExecutor.java#L177 from Nov 9, 2021 tag contains it.

Yes, contains. But it's declared as "private" here.

from v.0.13.4 it's `private` and has ` @Nullable IDocument document`:
```
private static CompletableFuture<Object> executeCommandClientSide(@NonNull Command command, @Nullable IDocument document) 
```
from v.0.16.0 it's `public`, but has `@NonNull IDocument document`:
```
public static CompletableFuture<Object> executeCommandClientSide(@NonNull Command command, @NonNull IDocument document) 
```

**Comment by mickaelistria** [comment]
I agree that the min version of LSP4E should be changed, or there is a strong risk we see runtime issues without it.

**Pull request merged**
